[package]
name = "cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0.12.1"
prost-types = "0.12.1"
rpassword = "7.2.0"
tokio = {verseion = "1.32.0", features = ["macros", "rt-multi-thread"]}
tonic = "0.10.1"

[build-dependencies]
tonic-build = "0.10.1"
